<?php
//各ページよりCSSとJSを読み込む
add_action('wp_enqueue_scripts','chalon_enqueue');

function chalon_enqueue(){
    //全ページ共通のCSSの読み込み（google fonts、icon font、reset.css、common.css）
    wp_enqueue_style(
        'google-fonts',
        'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&family=Noto+Serif+JP:wght@400;700&display=swap'
    );
    wp_enqueue_style(
        'google-icon',
        'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0'
    );
    wp_enqueue_style(
        'chalon-reset',
        get_template_directory_uri().'/css/common/reset.css',
        [],
        filemtime(get_theme_file_path('/css/common/reset.css'))
    );
    wp_enqueue_style(
        'chalon-common',
        get_template_directory_uri().'/css/common/common.css',
        [],
        filemtime(get_theme_file_path('/css/common/common.css'))
    );

    //全ページ共通のjsの読み込み（jquery、common.js）
    wp_enqueue_script(
        'chalon-jquery',
        'https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js',
        [],
        '',
        true
    );
    wp_enqueue_script(
        'chalon-common',
        get_template_directory_uri().'/js/common.js',
        [],
        filemtime(get_theme_file_path('/js/common.js')),
        true
    );

    if(is_front_page()){
        //topページで使うCSSを読み込む（slick、slick-theme、top.css）
        wp_enqueue_style(
            'slick-theme',
            'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.min.css'
        );
        wp_enqueue_style(
            'slick',
            'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.css'
        );
        wp_enqueue_style(
            'chalon-top',
            get_template_directory_uri().'/css/page/top.css',
            [],
            filemtime(get_theme_file_path('/css/page/top.css'))
        );
        //topページで使うjsを読み込む（slick、top.js）
        wp_enqueue_script(
            'slick',
            'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js',
            [],
            '',
            true
        );
        wp_enqueue_script(
            'chalon-top',
            get_template_directory_uri().'/js/top.js',
            [],
            filemtime(get_theme_file_path('/js/top.js')),
            true
        );
    }else{
        wp_enqueue_style(
            'chalon-under',
            get_template_directory_uri().'/css/common/under.css',
            [],
            filemtime(get_theme_file_path('/css/common/under.css'))
        );
    }
    //当店について
    if(is_page('about')){
        wp_enqueue_style(
            'chalon-about',
            get_template_directory_uri().'/css/page/about.css',
            [],
            filemtime(get_theme_file_path('/css/page/about.css'))
        );
        wp_enqueue_script(
            'chalon-about',
            get_template_directory_uri().'/js/about.js',
            [],
            filemtime(get_theme_file_path('/js/about.js')),
            true
        );
    }
    //アクセス
    if(is_page('access')){
        wp_enqueue_style(
            'chalon-access',
            get_template_directory_uri().'/css/page/access.css',
            [],
            filemtime(get_theme_file_path('/css/page/access.css'))
        );
    }
    //お申し込み、確認、送信
    if(is_page(['trial','check','thanks'])){
        wp_enqueue_style(
            'chalon-trial',
            get_template_directory_uri().'/css/page/trial.css',
            [],
            filemtime(get_theme_file_path('/css/page/trial.css'))
        );
    }

    //お報せ
    if(is_singular('post')){
        wp_enqueue_style(
            'chalon-news',
            get_template_directory_uri().'/css/page/news.css',
            [],
            filemtime(get_theme_file_path('/css/page/news.css'))
        );
    }

    //各メニュー
    if(is_singular('menu')){
        wp_enqueue_style(
            'chalon-menu-single',
            get_template_directory_uri().'/css/page/menu_single.css',
            [],
            filemtime(get_theme_file_path('/css/page/menu_single.css'))
        );
    }

    //メニューアーカイブ
    if(is_post_type_archive('menu')){
        wp_enqueue_style(
            'chalon-menu',
            get_template_directory_uri().'/css/page/menu.css',
            [],
            filemtime(get_theme_file_path('/css/page/menu.css'))
        );
    }

    //お菓子教室
    if(is_page('lesson')){
        wp_enqueue_style(
            'slick-theme',
            'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.min.css'
        );
        wp_enqueue_style(
            'slick',
            'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.css'
        );

        wp_enqueue_style(
            'chalon-lesson',
            get_template_directory_uri().'/css/page/lesson.css',
            [],
            filemtime(get_theme_file_path('/css/page/lesson.css'))
        );

        wp_enqueue_script(
            'slick',
            'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js',
            [],
            '',
            true
        );
        wp_enqueue_script(
            'chalon-lesson',
            get_template_directory_uri().'/js/lesson.js',
            [],
            filemtime(get_theme_file_path('/js/lesson.js')),
            true
        );

    }
    //各voice
    if(is_singular('voice')){
        wp_enqueue_style(
            'chalon-voice',
            get_template_directory_uri().'/css/page/voice.css',
            [],
            filemtime(get_theme_file_path('/css/page/voice.css'))
        );
    }

}///////CSS・JSの読み込みここまで//////////////

//SVGファイルをアップロード出来るようにする
add_action('upload_mimes','chalon_mimes');

function chalon_mimes($file_types){
    $file_types['svg'] = 'image/svg+xml';
    return $file_types;
}